apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 128Mi
              cpu: 0.3
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-config
              subPath: nginx.conf
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter
          args:
            - '-nginx.scrape-uri=http://localhost/metrics'
          ports:
            - containerPort: 9113
              name: metrics
          resources:
            limits:
              memory: 128Mi
              cpu: 0.3
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config