apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: contatos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: contatos-app
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: contatos-app
    spec:
      containers:
        - name: mysql-pod
          image: mysql
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_root_password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql_database
          - name: TZ
            value: "America/Sao_Paulo"