baseURL="https://rotoku.github.io/"
languageCode="pt-br"
title="Kumabe's GitHub Pages"
theme=["docsy"]

# emoji
enableEmoji=true

rss_sections = ["blog"]

# Language settings
contentDir = "content/pt-br"
defaultContentLanguage = "pt-br"
[languages]
[languages.pt-br]
title="Kumabe's GitHub Pages"
languageName="Português"
# weight used for sorting
weight=1

staticDir = ["static"]

# mermaid
[params.mermaid]
enable = true



[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "User mailing list"
  url = "https://example.org/mail"
  icon = "fa fa-envelope"
  desc = "Discussion and help from your fellow users"
[[params.links.user]]
  name ="Twitter"
  url = "https://twitter.com/rtkumabe"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
  name = "Stack Overflow"
  url = "https://example.org/stack"
  icon = "fab fa-stack-overflow"
  desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/rotoku"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Slack"
  url = "https://example.org/slack"
  icon = "fab fa-slack"
  desc = "Chat with other project developers"
[[params.links.developer]]
  name = "Developer mailing list"
  url = "https://example.org/mail"
  icon = "fa fa-envelope"
  desc = "Discuss development issues around the project"


# hugo module configuration

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false    