apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-sleeper
  name: ubuntu-sleeper
spec:
  containers:
  - image: ubuntu
    name: ubuntu-sleeper
    command: ["sleep"]
    args: ["10"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
