apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteMany"
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/volume/nginx
