apiVersion: v1
data:
  DB_USERNAME: Y2FzZS0wMDE=
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
  DB_NAME: Y2FzZS0wMDE=
  DB_HOSTNAME: ZGItbWFyaWFkYi1zZXJ2aWNlLmRhdGFiYXNlLnN2Yy5jbHVzdGVyLmxvY2Fs
kind: Secret
metadata:
  creationTimestamp: null
  name: be-products-secret
  namespace: backend