apiVersion: v1
kind: Service
metadata:
  name: myapp-service-nodeport
spec:
  type: NodePort
  ports:
    - targetPort: 80 # assume the same port as the port
      port: 80 # required
      nodePort: 30008 # random from 30000 - 32767
  selector:
    env: production