apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication-controller
  labels:
    app: myapp-replication-controller
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-replication-controller
      labels:
        app: myapp-replication-controller
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0-alpine