apiVersion: v1
king: Secret
metadata:
  name: kumabes-org-dockerhub-secret
type: kubernetes.io/dockerconfigjson  
data:
  .dockerconfigjson: ewoJInVzZXJuYW1lIjogInRvbSIsCgkidXNlcm5hbWUiOiAidG9tIiwKCSJwYXNzd29yZCI6ICJwYXNzd29yZCIsCgkicmVhbG1vciI6ICJodHRwczovL2RvY2tlci5odWIvIgp9
