apiVersion: v1
data:
  nginx.conf: "user  nginx;\nworker_processes  auto;\n\nerror_log  /var/log/nginx/error.log
    notice;\npid        /var/run/nginx.pid;\n\n\nevents {\n    worker_connections
    \ 1024;\n}\n\nhttp {\n    server {\n        listen       80;\n        listen  [::]:80;
    \       \n        listen 443 ssl;\n        server_name  localhost;\n        ssl_certificate
    /etc/nginx/ssl/certificado.crt;\n        ssl_certificate_key /etc/nginx/ssl/chave_privada.key;\n\n
    \       location / {\n            return 200 'Olá terraqueos e extraterrestres!\\n';\n
    \           add_header Content-Type text/plain;\n        }\n    }\n}"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-10T11:19:38Z"
  name: nginx-config
  namespace: default
  resourceVersion: "266843"
  uid: 012d16ba-385e-4f28-a1ed-5cbc8ec5d349
