apiVersion: v1
kind: Pod
metadata:
  name: kumabes-org-pod
spec:
  containers:
  - name: kumabes-org-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: kumabes-org-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: kumabes-org-secret
          key: password
