apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
  labels:
    app: nginx-configmap
spec:
  containers:
  - name: nginx-configmap
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config