apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-nfs
  labels:
    storage: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.20
    path: "/mnt/nfs"
  storageClassName: storage-class