apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  labels:
    storage: lento
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #Delete, Recycle
  hostPath:
    path: /mnt/data
  storageClassName: storage-class