apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:14.9-bullseye
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "sonarqube"
            - name: POSTGRES_PASSWORD
              value: "sonarqube"
            - name: POSTGRES_DB
              value: "sonarqube"  
            - name: TZ
              value: "America/Sao_Paulo"