apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: opaque
data:
  mysql_root_password: cm9vdA==
  mysql_user: Y29udGF0b3NfYXBw
  mysql_password: Y29udGF0b3NfYXBw
  mysql_database: Y29udGF0b3NfYXBw