apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue-green-svc
  name: blue-green-svc
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    tier: frontend
    case: bluegreen
  type: ClusterIP
status:
  loadBalancer: {}
