apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
spec:  
  containers:
  - image: busybox:1.36.1
    name: first
    command:
      - "sh"
      - "-c"
      - "echo 'Hello World!' && sleep 3600"
  - image: nginx
    name: second
    ports:
      - containerPort: 80
  - image: busybox:1.37
    name: thrird    
    command:
      - "sh"
      - "-c"
      - "echo 'Last Container' && sleep 3600"    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
