apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-busybox
  name: my-busybox
  namespace: dev2406
spec:
  nodeName: controlplane
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
  - image: busybox
    name: secret
    command:
      - sleep
      - "3600"
    resources: {}
    volumeMounts:
      - mountPath: /etc/secret-volume
        readOnly: true
        name: secret-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
