apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: default
spec:
  containers:
  - image: kodekloud/event-simulator
    name: webapp
    volumeMounts:
    - mountPath: /log
      name: webapp
  volumes:
  - name: webapp
    hostPath:
      path: /var/log/webapp
      type: Directory