apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contatos-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /contatos
        pathType: Prefix
        backend:
          service:
            name: contatos-app
            port:
              number: 3000