{{- with .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  labels:
    {{- range $.Values.serviceAccount.labels }}
    tier: {{ . }}
    {{- end }}
    app: webapp-color
{{- end }}