# Storage Request: 1Gi
# Access modes: ReadWriteMany
# pvc name = jekyll-site, namespace = development
# 'jekyll-site' PVC should be bound to the PersistentVolume called 'jekyll-site'.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi