apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
spec:
  containers:
  - image: nginx
    name: nginx
    
  - image: busybox
    name: busybox
    command:
    - "sh"
    - "-c"
    - "sleep 60"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
