apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: asia
  name: asia
  namespace: world
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: asia
  type: ClusterIP
status:
  loadBalancer: {}