apiVersion: v1
data:
  department: park
  level: "3"
  tree: birke
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"department":"park","level":"3","tree":"birke"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"birke","namespace":"default"}}
  creationTimestamp: "2024-10-20T22:54:14Z"
  name: birke
  namespace: default
  resourceVersion: "7164"
  uid: 945fba04-da41-4c94-a06c-2e26b31e3627