apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: minha-secret
      items:
        - key: user
          path: users.conf
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /data
        name: secret-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
