apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primeiropvc
  namespace: day1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi