apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  destination:
    namespace: arc-runners
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: "gha-runner-scale-set"
    repoURL: "ghcr.io/actions/actions-runner-controller-charts"
    targetRevision: "0.9.3"
    helm:
      parameters:
        - name: githubConfigUrl
          value: "https://github.com/kumabes-org"
        - name: githubConfigSecret.github_token
          value: "gh-app-arc-community"
        - name: maxRunners
          value: "10"
        - name: minRunners
          value: "1"
        - name: runnerGroup
          value: "default"
        - name: runnerScaleSetName
          value: "kumabes-runner-small"          
        - name: template.spec.containers[0].command[0]
          value: "/home/runner/run.sh"
        - name: template.spec.containers[0].image
          value: "ghcr.io/actions/actions-runner:2.318.0"
        - name: template.spec.containers[0].name
          value: "runner"