apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-systems
  namespace: argocd
spec:
  destination:
    namespace: arc-systems
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: gha-runner-scale-set-controller
    repoURL: "https://github.com/kumabes-org/argocd-example-apps.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true