apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-webapp-dev-project
  namespace: argocd
spec:
  destination:
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source:
    path: java-webapp
    repoURL: "https://github.com/kumabes-org/argocd-example-apps.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true