apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 30123 # Range: 30000-32677
  type: NodePort