apiVersion: v1
kind: Pod
metadata:
  name: example-baseline-pod-compliance
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  #     type: Localhost
  #     localhostProfile: profiles/audit.json
  containers:
    - image: nginx
      name: nginx
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true

      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "0.25"          
          memory: "1Gi"
        limits:          
          cpu: "0.25"
          memory: "1Gi"          
    