apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    # securityContext:
    #   allowPrivilegeEscalation: false

#(container "nginx" must set securityContext.allowPrivilegeEscalation=false),
#unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]),
#runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true),
#seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
